# WEB SCRAPING – ASSIGNMENT 4
![begin](https://media2.giphy.com/media/JVQYT5y5N8sYohDkkq/200w.gif?cid=82a1493bcfxdade5bnk93czjr18x23ulqhkq1qw0pqqtiwdh&rid=200w.gif&ct=s)

In [2]:
# import necessary libraries at once

import pandas as pd
import selenium
import time
from bs4 import BeautifulSoup 
from selenium import webdriver
from selenium.webdriver.common.by import By

from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys
import requests
import re

## 1. Scrape the details of most viewed videos on YouTube from Wikipedia.
#### Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos
#### You need to find following details:
    A) Rank
    B) Name
    C) Artist
    D) Upload date
    E) Views

In [2]:
# connect to webdriver
driver = webdriver.Chrome(r"C:/Users/DELL/Downloads/chromedriver_win32/chromedriver.exe")

# get webpage
driver.get(" https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")
driver.maximize_window()

<ipython-input-2-a9c4bb8ad0b6>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:/Users/DELL/Downloads/chromedriver_win32/chromedriver.exe")

In [3]:
#creating empty lists
Rank = []
Name = []
Artist = []
Upload_date = []
Views = []

In [4]:
#finding all the rank tags
rank = driver.find_elements_by_xpath('//*[@id="mw-content-text"]/div[1]/table[1]/tbody/tr/td[1]')[0:30]
rank[0:3]

<ipython-input-4-ddb2019a98b1>:2: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  rank = driver.find_elements_by_xpath('//*[@id="mw-content-text"]/div[1]/table[1]/tbody/tr/td[1]')[0:30]

In [12]:
#scraping the Rank
for i in driver.find_elements_by_xpath("//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr/td[1]"):
    Rank.append(i.text)

#scraping the Name
for i in driver.find_elements_by_xpath("//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr/td[2]"):
    Name.append(i.text.split('[')[0])

#scraping the Artist
for i in driver.find_elements_by_xpath("//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr/td[3]"):
    Artist.append(i.text)

#scraping the upload date
for i in driver.find_elements_by_xpath("//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr/td[5]"):
    Upload_date.append(i.text)

#scraping the number of views
for i in driver.find_elements_by_xpath("//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr/td[4]"):
    Views.append(i.text)

<ipython-input-12-9f956b635dc7>:2: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr/td[1]"):
<ipython-input-12-9f956b635dc7>:6: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr/td[2]"):
<ipython-input-12-9f956b635dc7>:10: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr/td[3]"):
<ipython-input-12-9f956b635dc7>:14: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr/td[5]"):
<ipython-input-12-9f956b635dc7>:18: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  for i in driver.find_elements_by_xpath("//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr/td[4]"):

In [9]:
Rank=Rank[0:30]
Name=Name[0:30]
Artist=Artist[0:30]

In [10]:
len(Rank),len(Name),len(Artist),len(Upload_date),len(Views)

(30, 30, 30, 30, 30)

In [11]:
Yotube_Most_Views={'Rank':Rank,'Name':Name,'Artist':Artist,'Uploaded Date':Upload_date,'Views':Views}
Yotube_Most_Views=pd.DataFrame(data=Yotube_Most_Views)
Yotube_Most_Views

,Rank,Name,Artist,Uploaded Date,Views
0,1.,"""Baby Shark Dance""",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",9.98
1,2.,"""Despacito""",Luis Fonsi,"January 12, 2017",7.70
2,3.,"""Johny Johny Yes Papa""",LooLoo Kids,"October 8, 2016",6.09
3,4.,"""Shape of You""",Ed Sheeran,"January 30, 2017",5.58
4,5.,"""See You Again""",Wiz Khalifa,"April 6, 2015",5.38
5,6.,"""Bath Song""",Cocomelon – Nursery Rhymes,"May 2, 2018",4.84
6,7.,"""Learning Colors – Colorful Eggs on a Farm""",Miroshka TV,"February 27, 2018",4.55
7,8.,"""Masha and the Bear – Recipe for Disaster""",Get Movies,"January 31, 2012",4.48
8,9.,"""Uptown Funk""",Mark Ronson,"November 19, 2014",4.42
9,10.,"""Phonics Song with Two Words""",ChuChu TV,"March 6, 2014",4.40
10,11.,"""Gangnam Style""",Psy,"July 15, 2012",4.30
11,12.,"""Dame Tu Cosita""",El Chombo,"April 5, 2018",3.79
12,13.,"""Sugar""",Maroon 5,"January 14, 2015",3.62
13,14.,"""Sorry""",Justin Bieber,"October 22, 2015",3.50
14,15.,"""Roar""",Katy Perry,"September 5, 2013",3.50
15,16.,"""Wheels on the Bus""",Cocomelon – Nursery Rhymes,"May 24, 2018",3.48
16,17.,"""Counting Stars""",OneRepublic,"May 31, 2013",3.48
17,18.,"""Thinking Out Loud""",Ed Sheeran,"October 7, 2014",3.39
18,19.,"""Girls Like You""",Maroon 5,"May 31, 2018",3.21
19,20.,"""Faded""",Alan Walker,"December 3, 2015",3.21
20,21.,"""Dark Horse""",Katy Perry,"February 20, 2014",3.20
21,22.,"""Axel F""",Crazy Frog,"June 16, 2009",3.17
22,23.,"""Let Her Go""",Passenger,"July 25, 2012",3.15
23,24.,"""Bailando""",Enrique Iglesias,"April 11, 2014",3.15
24,25.,"""Lean On""",Major Lazer,"March 22, 2015",3.15
25,26.,"""Shake It Off""",Taylor Swift,"August 18, 2014",3.13
26,27.,"""Baa Baa Black Sheep""",Cocomelon – Nursery Rhymes,"June 25, 2018",3.06
27,28.,"""Perfect""",Ed Sheeran,"November 9, 2017",3.06
28,29.,"""Waka Waka (This Time for Africa)""",Shakira,"June 4, 2010",3.03
29,30.,"""Mi Gente""",J Balvin,"June 29, 2017",3.02

In [19]:
driver.close()

## 2. Scrape the details team India’s international fixtures from bcci.tv.
#### Url = https://www.bcci.tv/.
#### You need to find following details:
    A) Match title(I.e. 1st ODI)
    B) Series
    C) Place
    D) Date
    E) Time
Note: - From bcci.tv home page you have reach to the international fixture page through cod

In [32]:
# connect to webdriver
driver = webdriver.Chrome(r"C:/Users/DELL/Downloads/chromedriver_win32/chromedriver.exe")

# get webpage
driver.get(" https://www.bcci.tv/")
driver.maximize_window()

<ipython-input-32-0efdd93f0b1e>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:/Users/DELL/Downloads/chromedriver_win32/chromedriver.exe")

In [37]:
#clickin on International tab
International = driver.find_element_by_xpath('//a[@class = "nav-link  "]') # click button
International.click()

<ipython-input-37-71a01ce5d79c>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  searchbtn = driver.find_element_by_xpath('//a[@class = "nav-link  "]') # click search button

In [46]:
#clickin on ODI
ODI = driver.find_element_by_xpath('//div[@class = "customSelecBox matchFormatDropDown openSBox"]').click()
ODI_I = driver.find_element_by_xpath('//div[@class ="cSBListItems ng-scope"][2]').click()

<ipython-input-46-debea1e9fcba>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  ODI = driver.find_element_by_xpath('//div[@class = "customSelecBox matchFormatDropDown openSBox"]').click()
<ipython-input-46-debea1e9fcba>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  ODI_I = driver.find_element_by_xpath('//div[@class ="cSBListItems ng-scope"][2]').click()

In [49]:
# Scrape all Name Tag

NAME=[]
name_tag=driver.find_elements_by_xpath("//div[@class='fixture-card-top']/h5[2]")

for i in name_tag:
    ntitle=i.text
    NAME.append(ntitle)
    
NAME

<ipython-input-49-2821108e6485>:4: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  name_tag=driver.find_elements_by_xpath("//div[@class='fixture-card-top']/h5[2]")

['INDIA TOUR OF SOUTH AFRICA ODI SERIES 2021/22',
 'INDIA TOUR OF SOUTH AFRICA ODI SERIES 2021/22',
 'INDIA TOUR OF SOUTH AFRICA ODI SERIES 2021/22',
 'WEST INDIES TOUR OF INDIA ODI SERIES 2022',
 'WEST INDIES TOUR OF INDIA ODI SERIES 2022',
 'WEST INDIES TOUR OF INDIA ODI SERIES 2022']

In [50]:
#Scrape all Place tag

PLACE=[]
place_tag=driver.find_elements_by_xpath("//div[@class='fixture-card-bottom']")
for i in place_tag:
    ptitle=i.text.split("-")[1]
    PLACE.append(ptitle)
PLACE

<ipython-input-50-a5c5d9ada242>:2: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  place_tag=driver.find_elements_by_xpath("//div[@class='fixture-card-bottom']")

[' Boland Park, Paarl\nMatch Centre',
 ' Boland Park, Paarl\nMatch Centre',
 ' Newlands, Cape Town\nMatch Centre',
 ' NARENDRA MODI STADIUM, Ahmedabad\nMatch Centre',
 ' Sawai Mansingh Stadium, Jaipur\nMatch Centre',
 ' Eden Gardens, Kolkata\nMatch Centre']

In [51]:
#Scrape all title tag

TITLE=[]
title_tag=driver.find_elements_by_xpath("//div[@class='fixture-card-bottom']")
for i in title_tag:
    ttitle=i.text.split("-")[0]
    TITLE.append(ttitle)
TITLE

<ipython-input-51-de75689624d5>:2: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  title_tag=driver.find_elements_by_xpath("//div[@class='fixture-card-bottom']")

['1st ODI ', '2nd ODI ', '3rd ODI ', '1st ODI ', '2nd ODI ', '3rd ODI ']

In [52]:
# Scrape All Date tag

DATE=[]
date_tag=driver.find_elements_by_xpath("//div[@class='match-card-left match-schedule']")
for i in date_tag:
    date=i.text
    DATE.append(date)
DATE

<ipython-input-52-6a5e11231a12>:2: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  date_tag=driver.find_elements_by_xpath("//div[@class='match-card-left match-schedule']")

['19 JAN 2022',
 '21 JAN 2022',
 '23 JAN 2022',
 '6 FEB 2022',
 '9 FEB 2022',
 '12 FEB 2022']

In [54]:
# Scrape All Time tag

TIME=[]
time_tag=driver.find_elements_by_xpath("//div[@class='match-card-right match-schedule ']")
for i in time_tag:
    timetag=i.text
    TIME.append(timetag)
TIME

<ipython-input-54-e2466acf67f0>:4: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  time_tag=driver.find_elements_by_xpath("//div[@class='match-card-right match-schedule ']")

['2:00 PM IST',
 '2:00 PM IST',
 '2:00 PM IST',
 '9:30 AM IST',
 '9:30 AM IST',
 '9:30 AM IST']

In [56]:
# Create Dataframe

Fixtures=pd.DataFrame({})
Fixtures['Title']=TITLE
Fixtures['Name']=NAME
Fixtures['Place']=PLACE
Fixtures['Date']=DATE
Fixtures['Time']=TIME
Fixtures

,Title,Name,Place,Date,Time
0,1st ODI,INDIA TOUR OF SOUTH AFRICA ODI SERIES 2021/22,"Boland Park, Paarl\nMatch Centre",19 JAN 2022,2:00 PM IST
1,2nd ODI,INDIA TOUR OF SOUTH AFRICA ODI SERIES 2021/22,"Boland Park, Paarl\nMatch Centre",21 JAN 2022,2:00 PM IST
2,3rd ODI,INDIA TOUR OF SOUTH AFRICA ODI SERIES 2021/22,"Newlands, Cape Town\nMatch Centre",23 JAN 2022,2:00 PM IST
3,1st ODI,WEST INDIES TOUR OF INDIA ODI SERIES 2022,"NARENDRA MODI STADIUM, Ahmedabad\nMatch Centre",6 FEB 2022,9:30 AM IST
4,2nd ODI,WEST INDIES TOUR OF INDIA ODI SERIES 2022,"Sawai Mansingh Stadium, Jaipur\nMatch Centre",9 FEB 2022,9:30 AM IST
5,3rd ODI,WEST INDIES TOUR OF INDIA ODI SERIES 2022,"Eden Gardens, Kolkata\nMatch Centre",12 FEB 2022,9:30 AM IST

In [57]:
# close the driver
driver.close()

## 3. Scrape the details of selenium exception from guru99.com.
#### Url = https://www.guru99.com/
#### You need to find following details:
    A) Name
    B) Description
#### Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [58]:
# connect to webdriver
driver = webdriver.Chrome(r"C:/Users/DELL/Downloads/chromedriver_win32/chromedriver.exe")

# get webpage
driver.get("https://www.guru99.com/")
driver.maximize_window()

<ipython-input-58-8fc1154f0449>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:/Users/DELL/Downloads/chromedriver_win32/chromedriver.exe")

In [76]:
# Click Selenium Button
Selenium = driver.find_element_by_xpath('//div[@class = "wp-block-kadence-column inner-column-2 kadence-column_f38d98-3a"]') # click button
try:
    Selenium.click()
except ElementNotInteractableException:#handling element not clickable exception
    driver.get(Selenium.get_attribute('href'))

<ipython-input-76-8bfd1daaa8c5>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Selenium = driver.find_element_by_xpath('//div[@class = "wp-block-kadence-column inner-column-2 kadence-column_f38d98-3a"]') # click button

In [80]:
# Click selenium exception handling  Button
exception_handling = driver.find_element_by_xpath("//a[@title='Selenium Exception Handling (Common Exceptions List)']")
try:
    exception_handling.click()
except ElementNotInteractableException:  #if the above code doesn't work/is not clickable then, the below code will handle it
    driver.get(exception_handling.get_attribute('href'))

<ipython-input-80-a2db782a762a>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  exception_handling = driver.find_element_by_xpath("//a[@title='Selenium Exception Handling (Common Exceptions List)']")

In [83]:
# Scrape all names tag
names=[]
try:
    name=driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[1]")
    for i in name[1:]:
        names.append(i.text)
except NoSuchElementException:
    names.append('N/A')

<ipython-input-83-b2fcadd93c13>:4: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  name=driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[1]")

In [84]:
# Scrape all Description tag

desc=[]
try:
    descrip=driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[2]")
    for i in descrip[1:]:
        desc.append(i.text)
except NoSuchElementException:
    desc.append('No details available')

<ipython-input-84-5c39ff74c1d3>:5: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  descrip=driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[2]")

In [87]:
#create Dataframe

dataframe=pd.DataFrame()
dataframe['Exception name']=names
dataframe['Description']=desc
dataframe

,Exception name,Description
0,ElementNotSelectableException,This Selenium exception occurs when an element...
1,NoSuchElementException,This Exception occurs if an element could not ...
2,NoSuchFrameException,This Exception occurs if the frame target to b...
3,NoAlertPresentException,This Exception occurs when you switch to no pr...
4,NoSuchWindowException,This Exception occurs if the window target to ...
5,StaleElementReferenceException,This Selenium exception occurs happens when th...
6,SessionNotFoundException,The WebDriver is acting after you quit the bro...
7,TimeoutException,Thrown when there is not enough time for a com...
8,WebDriverException,This Exception takes place when the WebDriver ...
9,ConnectionClosedException,This type of Exception takes place when there ...
10,ElementClickInterceptedException,The command may not be completed as the elemen...
11,ElementNotInteractableException,This Selenium exception is thrown when any ele...
12,ErrorInResponseException,This happens while interacting with the Firefo...
13,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
14,ImeActivationFailedException,This expectation will occur when IME engine ac...
15,ImeNotAvailableException,It takes place when IME support is unavailable.
16,InsecureCertificateException,Navigation made the user agent to hit a certif...
17,InvalidArgumentException,It occurs when an argument does not belong to ...
18,InvalidCookieDomainException,This happens when you try to add a cookie unde...
19,InvalidCoordinatesException,This type of Exception matches an interacting ...
20,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
21,InvalidSessionIdException,This Exception took place when the given sessi...
22,InvalidSwitchToTargetException,This occurs when the frame or window target to...
23,JavascriptException,This issue occurs while executing JavaScript g...
24,JsonException,It occurs when you afford to get the session w...
25,NoSuchAttributeException,This kind of Exception occurs when the attribu...
26,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
27,NoSuchContextException,ContextAware does mobile device testing.
28,NoSuchCookieException,This Exception occurs when no cookie matching ...
29,NotFoundException,This Exception is a subclass of WebDriverExcep...
30,RemoteDriverServerException,This Selenium exception is thrown when the ser...
31,ScreenshotException,It is not possible to capture a screen.
32,SessionNotCreatedException,It happens when a new session could not be suc...
33,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
34,UnexpectedTagNameException,Happens if a support class did not get a web e...
35,UnhandledAlertException,This expectation occurs when there is an alert...
36,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
37,UnknownMethodException,This Exception happens when the requested comm...
38,UnreachableBrowserException,This Exception occurs only when the browser is...
39,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

In [88]:
#Close the driver
driver.close()

## 4. Scrape the details of State-wise GDP of India from statisticstime.com.
#### Url = http://statisticstimes.com/
#### You have to find following details:
    A) Rank
    B) State
    C) GSDP
    D) GSDP
    E) Share
    F) GDP
#### Note: - From statisticstimes home page you have to reach to economy page through code.

In [89]:
# connect to webdriver
driver = webdriver.Chrome(r"C:/Users/DELL/Downloads/chromedriver_win32/chromedriver.exe")

# get webpage
driver.get(" http://statisticstimes.com/")
driver.maximize_window()

<ipython-input-89-e0d33f4ebeb5>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:/Users/DELL/Downloads/chromedriver_win32/chromedriver.exe")

In [92]:
# click Economy button

economy = driver.find_element_by_xpath("//*[@id='top']/div[2]/div[2]/button")
try:
    economy.click()
except ElementNotInteractableException:
    driver.get(economy.get_attribute('href'))

<ipython-input-92-aa326c11dd97>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  economy = driver.find_element_by_xpath("//*[@id='top']/div[2]/div[2]/button")

In [93]:
# click on GDP and and go to GDP page

gdp = driver.find_element_by_xpath("//*[@id='top']/div[2]/div[2]/div/a[3]")
try:
    gdp.click()
except ElementNotInteractableException:
    driver.get(gdp.get_attribute('href'))

<ipython-input-93-046d7f1cdb11>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  gdp = driver.find_element_by_xpath("//*[@id='top']/div[2]/div[2]/div/a[3]")

In [94]:
# click on GDP of Indian State

gdp_state = driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[2]/ul/li[1]/a")
try:
    gdp_state.click()
except ElementNotInteractableException:
    driver.get(gdp_state.get_attribute('href'))

<ipython-input-94-8df21f7b0aa8>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  gdp_state = driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[2]/ul/li[1]/a")

In [105]:
#Rank
rank=[i for i in range(1,len(state)+1)]

In [96]:
# Scrap all the states name
state=[]
try:
    name=driver.find_elements_by_xpath("//*[@id='table_id']/tbody/tr/td[2]")
    for i in name:
        state.append(i.text)
except NoSuchElementException:
    state.append('N/A')
except StaleElementReferenceException:
    state.append('N/A')

state

<ipython-input-96-af4e4872879b>:4: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  name=driver.find_elements_by_xpath("//*[@id='table_id']/tbody/tr/td[2]")

['Maharashtra',
 'Tamil Nadu',
 'Uttar Pradesh',
 'Gujarat',
 'Karnataka',
 'West Bengal',
 'Rajasthan',
 'Andhra Pradesh',
 'Telangana',
 'Madhya Pradesh',
 'Kerala',
 'Delhi',
 'Haryana',
 'Bihar',
 'Punjab',
 'Odisha',
 'Assam',
 'Chhattisgarh',
 'Jharkhand',
 'Uttarakhand',
 'Jammu & Kashmir',
 'Himachal Pradesh',
 'Goa',
 'Tripura',
 'Chandigarh',
 'Puducherry',
 'Meghalaya',
 'Sikkim',
 'Manipur',
 'Nagaland',
 'Arunachal Pradesh',
 'Mizoram',
 'Andaman & Nicobar Islands']

In [97]:
# Scrap all the GSDP of 20
gsdp20=[]
try:
    name=driver.find_elements_by_xpath("//*[@id='table_id']/tbody/tr/td[3]")
    for i in name:
        gsdp20.append(i.text)
except NoSuchElementException:
    gsdp20.append('N/A')
except StaleElementReferenceException:
    gsdp20.append('N/A')
gsdp20

<ipython-input-97-676d71b344cc>:4: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  name=driver.find_elements_by_xpath("//*[@id='table_id']/tbody/tr/td[3]")

['-',
 '1,845,853',
 '1,687,818',
 '-',
 '1,631,977',
 '1,253,832',
 '1,020,989',
 '972,782',
 '969,604',
 '906,672',
 '-',
 '856,112',
 '831,610',
 '611,804',
 '574,760',
 '521,275',
 '-',
 '329,180',
 '328,598',
 '-',
 '-',
 '165,472',
 '80,449',
 '55,984',
 '-',
 '38,253',
 '36,572',
 '32,496',
 '31,790',
 '-',
 '-',
 '26,503',
 '-']

In [99]:
# Scrap all the GSDP of 19
gsdp19=[]
try:
    name=driver.find_elements_by_xpath("//*[@id='table_id']/tbody/tr/td[4]")
    for i in name:
        gsdp19.append(i.text)
except NoSuchElementException:
    gsdp19.append('N/A')
except StaleElementReferenceException:
    gsdp19.append('N/A')
gsdp19

<ipython-input-99-c42cd5f8b758>:4: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  name=driver.find_elements_by_xpath("//*[@id='table_id']/tbody/tr/td[4]")

['2,632,792',
 '1,630,208',
 '1,584,764',
 '1,502,899',
 '1,493,127',
 '1,089,898',
 '942,586',
 '862,957',
 '861,031',
 '809,592',
 '781,653',
 '774,870',
 '734,163',
 '530,363',
 '526,376',
 '487,805',
 '315,881',
 '304,063',
 '297,204',
 '245,895',
 '155,956',
 '153,845',
 '73,170',
 '49,845',
 '42,114',
 '34,433',
 '33,481',
 '28,723',
 '27,870',
 '27,283',
 '24,603',
 '22,287',
 '-']

In [101]:
#Scrap Share details

share=[]
try:
    name=driver.find_elements_by_xpath("//*[@id='table_id']/tbody/tr/td[5]")
    for i in name:
        share.append(i.text)
except NoSuchElementException:
    share.append('N/A')
except StaleElementReferenceException:
    share.append('N/A')
    
share

<ipython-input-101-d0ffbbdc2e11>:5: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  name=driver.find_elements_by_xpath("//*[@id='table_id']/tbody/tr/td[5]")

['13.94%',
 '8.63%',
 '8.39%',
 '7.96%',
 '7.91%',
 '5.77%',
 '4.99%',
 '4.57%',
 '4.56%',
 '4.29%',
 '4.14%',
 '4.10%',
 '3.89%',
 '2.81%',
 '2.79%',
 '2.58%',
 '1.67%',
 '1.61%',
 '1.57%',
 '1.30%',
 '0.83%',
 '0.81%',
 '0.39%',
 '0.26%',
 '0.22%',
 '0.18%',
 '0.18%',
 '0.15%',
 '0.15%',
 '0.14%',
 '0.13%',
 '0.12%',
 '-']

In [103]:
#scrape gdp

gdp=[]
try:
    name=driver.find_elements_by_xpath("//*[@id='table_id']/tbody/tr/td[6]")
    for i in name:
        gdp.append(i.text)
except NoSuchElementException:
    gdp.append('N/A')
except StaleElementReferenceException:
    gdp.append('N/A')
gdp

<ipython-input-103-ce8f808775ca>:5: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  name=driver.find_elements_by_xpath("//*[@id='table_id']/tbody/tr/td[6]")

['399.921',
 '247.629',
 '240.726',
 '228.290',
 '226.806',
 '165.556',
 '143.179',
 '131.083',
 '130.791',
 '122.977',
 '118.733',
 '117.703',
 '111.519',
 '80.562',
 '79.957',
 '74.098',
 '47.982',
 '46.187',
 '45.145',
 '37.351',
 '23.690',
 '23.369',
 '11.115',
 '7.571',
 '6.397',
 '5.230',
 '5.086',
 '4.363',
 '4.233',
 '4.144',
 '3.737',
 '3.385',
 '-']

In [106]:
# Create dataframe
dataframe=pd.DataFrame()
dataframe['Rank']=rank
dataframe['State']=state
dataframe['GSDP at current price (19-20)']=gsdp20
dataframe['GSDP at current price (18-19)']=gsdp19
dataframe['Share (18-19)']=share
dataframe['GDP ($billion)']=gdp
dataframe.style.hide_index()

In [216]:
# close the driver
driver.close()

## 5. Scrape the details of trending repositories on Github.com.
#### Url = https://github.com/
#### You have to find the following details:
    A) Repository title
    B) Repository description
    C) Contributors count
    D) Language used
#### Note: - From the home page you have to click on the trending option from Explore menu through code.

In [217]:
# connect to webdriver
driver = webdriver.Chrome(r"C:/Users/DELL/Downloads/chromedriver_win32/chromedriver.exe")

# get webpage
driver.get(" https://github.com/")
driver.maximize_window()

<ipython-input-217-81d94754b9a4>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:/Users/DELL/Downloads/chromedriver_win32/chromedriver.exe")

In [218]:
# Click on explore

explore = driver.find_element_by_xpath('//li[@class = "mr-0 mr-lg-3 position-relative flex-wrap flex-justify-between flex-items-center border-bottom border-lg-bottom-0 d-block d-lg-flex flex-lg-nowrap flex-lg-items-center"][4]')
try:
    explore.click()
    time.sleep(5)
except ElementNotInteractableException:
    driver.get(explore.get_attribute('href'))

<ipython-input-218-8c58ed5235fa>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  explore = driver.find_element_by_xpath('//li[@class = "mr-0 mr-lg-3 position-relative flex-wrap flex-justify-between flex-items-center border-bottom border-lg-bottom-0 d-block d-lg-flex flex-lg-nowrap flex-lg-items-center"][4]')

In [219]:
# Click on Trending

trending = driver.find_element_by_xpath('//*[@href="/trending"]')
try:
    driver.get(trending.get_attribute('href'))
except ElementNotInteractableException:
    driver.get(trending.get_attribute('href'))

<ipython-input-219-309202f49a73>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  trending = driver.find_element_by_xpath('//*[@href="/trending"]')

In [220]:
#scrap all names tag

names=[]
try:
    name=driver.find_elements_by_xpath("//*[@id='js-pjax-container']/div[3]/div/div[2]/article/h1/a")
    for i in name:
        names.append(i.text)
except NoSuchElementException:
    names.append('N/A')

<ipython-input-220-700df9994264>:5: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  name=driver.find_elements_by_xpath("//*[@id='js-pjax-container']/div[3]/div/div[2]/article/h1/a")

In [221]:
# scrap all description tag

desc=[]
try:
    description=driver.find_elements_by_xpath("//*[@id='js-pjax-container']/div[3]/div/div[2]/article/p")
    for i in description:
        desc.append(i.text)
except NoSuchElementException:
    desc.append('N/A')

<ipython-input-221-7c02987a1446>:5: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  description=driver.find_elements_by_xpath("//*[@id='js-pjax-container']/div[3]/div/div[2]/article/p")

In [222]:
urls=[]
counts=[]
match_page=driver.find_elements_by_xpath('//*[@id="js-pjax-container"]/div[3]/div/div[2]/article/h1/a')
for i in match_page:
    urls.append(i.get_attribute('href'))

<ipython-input-222-30189b7adceb>:3: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  match_page=driver.find_elements_by_xpath('//*[@id="js-pjax-container"]/div[3]/div/div[2]/article/h1/a')

In [223]:
#Scrap all language tag

lang=[]
try:
    for i in urls:
        driver.get(i)
        count =driver.find_element_by_xpath('//*[@id="repo-content-pjax-container"]/div/div[2]/div[2]')    
        listy=count.text.split('\n')
        if 'Languages' in listy:
            lang.append(listy[listy.index('Languages')+1])
        else:
            lang.append('N/A')
except NoSuchElementException:
    lang.append('N/A')

<ipython-input-223-3f06775191dd>:7: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  count =driver.find_element_by_xpath('//*[@id="repo-content-pjax-container"]/div/div[2]/div[2]')

In [224]:
counts=[]
try:
    for i in urls:
        driver.get(i)
        count =driver.find_element_by_xpath('//*[@id="repo-content-pjax-container"]/div/div[2]/div[2]')    
        listy=count.text.split('\n')
        for j in listy:
            if j.split()[0]=='Contributors':
                counts.append(j.split()[1])
                break
        else:
            counts.append('N/A')
except NoSuchElementException:
    counts.append('N/A')

<ipython-input-224-25a0fbf7811e>:5: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  count =driver.find_element_by_xpath('//*[@id="repo-content-pjax-container"]/div/div[2]/div[2]')

In [225]:
len(names),len(desc),len(lang),len(counts)

(25, 24, 25, 25)

In [230]:
# create dataframe

dataframe=pd.DataFrame()
dataframe['Repository title']=names[0:24]
dataframe['Repository description']=desc[0:24]
dataframe['Language used']=lang[0:24]
dataframe['Contributors count']=counts[0:24]
dataframe

,Repository title,Repository description,Language used,Contributors count
0,bevyengine / bevy,A refreshingly simple data-driven game engine ...,Rust,320
1,Asabeneh / 30-Days-Of-JavaScript,30 days of JavaScript programming challenge is...,JavaScript,18
2,QSCTech / zju-icicles,浙江大学课程攻略共享计划,HTML,85
3,TheAlgorithms / Python,All Algorithms implemented in Python,Python,792
4,solana-labs / solana,"Web-Scale Blockchain for fast, secure, scalabl...",Rust,262
5,freeCodeCamp / freeCodeCamp,freeCodeCamp.org's open-source codebase and cu...,JavaScript,"4,373"
6,arendst / Tasmota,Alternative firmware for ESP8266 with easy con...,C,215
7,microsoft / PowerToys,Windows system utilities to maximize productivity,C#,262
8,521xueweihan / HelloGitHub,"分享 GitHub 上有趣、入门级的开源项目。Share interesting, entr...",Python,11
9,TheAlgorithms / Java,All Algorithms implemented in Java,Java,336
10,DarkCoderSc / PowerRemoteDesktop,Remote Desktop entirely coded in PowerShell.,PowerShell,2
11,xmu-xiaoma666 / External-Attention-pytorch,🍀 Pytorch implementation of various Attention ...,Python,3
12,FastVM / minivm,A VM That is Dynamic and Fast,C,4
13,irbigdata / data-dockerfiles,a curated list of docker-compose files prepare...,Jupyter Notebook,N/A
14,PKUanonym / REKCARC-TSC-UHT,清华大学计算机系课程攻略 Guidance for courses in Departmen...,HTML,43
15,sunym1993 / flash-linux0.11-talk,你管这破玩意叫操作系统源码 — 像小说一样品读 Linux 0.11 核心代码,C,14
16,megadose / holehe,holehe allows you to check if the mail is used...,Python,14
17,Anarios / return-youtube-dislike,Chrome extension to return youtube dislikes,JavaScript,60
18,faridrashidi / kaggle-solutions,🏅 Collection of Kaggle Solutions and Ideas 🏅,HTML,N/A
19,paralax / awesome-cybersecurity-internships,a list of cybersecurity internships,N/A,8
20,Klipper3d / klipper,Klipper is a 3d-printer firmware,C,266
21,jeecgboot / jeecg-boot,「企业级低代码平台」前后端分离架构SpringBoot 2.x，SpringCloud，An...,Java,9
22,VGVentures / slide_puzzle,❤️中国科学技术大学课程资源,Dart,4
23,USTC-Resource / USTC-Course,Get eBPF programs running from the cloud to th...,C++,9

In [67]:
# Close the driver
driver.close()

## 6. Scrape the details of top 100 songs on billiboard.com.
#### Url = https:/www.billboard.com/
#### You have to find the following details:
    A) Song name
    B) Artist name
    C) Last week rank
    D) Peak rank
    E) Weeks on board
#### Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [68]:
# connect to webdriver
driver = webdriver.Chrome(r"C:/Users/DELL/Downloads/chromedriver_win32/chromedriver.exe")

# get webpage
driver.get(" https:/www.billboard.com/")
driver.maximize_window()

<ipython-input-68-0a45cfd53a30>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:/Users/DELL/Downloads/chromedriver_win32/chromedriver.exe")

In [75]:
#Clicking on hot 100
url=driver.find_elements_by_xpath("//a[@class='c-link  lrv-a-unstyle-link lrv-u-font-size-18@desktop lrv-u-color-grey:hover u-color-brand-secondary:hover@desktop-max u-padding-a-1@desktop-max lrv-u-padding-tb-025 lrv-u-display-block']")
urls=url[0].get_attribute('href')
driver.get(urls)

<ipython-input-75-3b8f7300af7b>:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  url=driver.find_elements_by_xpath("//a[@class='c-link  lrv-a-unstyle-link lrv-u-font-size-18@desktop lrv-u-color-grey:hover u-color-brand-secondary:hover@desktop-max u-padding-a-1@desktop-max lrv-u-padding-tb-025 lrv-u-display-block']")

In [76]:
#Scrap all tags

Name=[]
Name.append(driver.find_element_by_xpath("//h3[@class='c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 u-font-size-23@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-245 u-max-width-230@tablet-only u-letter-spacing-0028@tablet']").text)
Artist=[]
Artist.append(driver.find_element_by_xpath("//span[@class='c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only u-font-size-20@tablet']").text)
rank=[]
rankTag=driver.find_elements_by_xpath("//span[@class='c-label  a-font-primary-bold-l a-font-primary-m@mobile-max u-font-weight-normal@mobile-max lrv-u-padding-tb-050@mobile-max u-font-size-32@tablet']")
rank.extend([i.text for i in rankTag[:3]])

<ipython-input-76-d6611ce43f8e>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Name.append(driver.find_element_by_xpath("//h3[@class='c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 u-font-size-23@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-245 u-max-width-230@tablet-only u-letter-spacing-0028@tablet']").text)
<ipython-input-76-d6611ce43f8e>:4: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Artist.append(driver.find_element_by_xpath("//span[@class='c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only u-font-size-20@tablet']").text)
<ipython-input-76-d6611ce43f8e>:6: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  rankTag=driver.find_elements_by_xpath("//span[@class='c-label  a-font-primary-bold-l a-font-primary-m@mobile-max u-font-weight-normal@mobile-max lrv-u-padding-tb-050@mobile-max u-font-size-32@tablet']")

In [77]:
#Scrap all tags
nameTag=driver.find_elements_by_xpath("//h3[@class='c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 lrv-u-font-size-18@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-330 u-max-width-230@tablet-only']")
Name.extend([i.text for i in nameTag])
artistTag=driver.find_elements_by_xpath("//span[@class='c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only']")
Artist.extend([i.text for i in artistTag])
Rank=[]
RankTag=driver.find_elements_by_xpath("//span[@class='c-label  a-font-primary-m lrv-u-padding-tb-050@mobile-max']")
Rank.extend([i.text for i in RankTag])

<ipython-input-77-b976bc184712>:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  nameTag=driver.find_elements_by_xpath("//h3[@class='c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 lrv-u-font-size-18@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-330 u-max-width-230@tablet-only']")
<ipython-input-77-b976bc184712>:3: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  artistTag=driver.find_elements_by_xpath("//span[@class='c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only']")
<ipython-input-77-b976bc184712>:6: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  RankTag=driver.find_elements_by_xpath("//span[@class='c-label  a-font-primary-m lrv-u-padding-tb-050@mobile-max']")

In [78]:
# removing ''
for i in Rank:
    if i=='':
        Rank.remove(i)

In [79]:
# slicing as per requirement
lastweekpos=Rank[0::3]
lastweekpos.insert(0,rank[0])
peakPos=Rank[1::3]
peakPos.insert(0,rank[1])
weeksonBoard=Rank[2::3]
weeksonBoard.insert(0,rank[2])

In [81]:
#check length of all
len(Name),len(Artist),len(lastweekpos),len(peakPos),len(weeksonBoard)

(100, 100, 133, 133, 133)

In [83]:
# Create Dataframe
df=pd.DataFrame()
df['SongName']=Name
df['ArtistName']=Artist
df['Last Week']=lastweekpos[0:100]
df["PeekPosition"]=peakPos[0:100]
df['Weeks On board']=weeksonBoard[0:100]
df

,SongName,ArtistName,Last Week,PeekPosition,Weeks On board
0,All I Want For Christmas Is You,Mariah Carey,1,1,51
1,Easy On Me,Adele,5,1,12
2,Rockin' Around The Christmas Tree,Brenda Lee,2,2,45
3,Jingle Bell Rock,Bobby Helms,3,3,42
4,A Holly Jolly Christmas,Burl Ives,4,4,26
...,...,...,...,...,...
95,Beers On Me,"Dierks Bentley, Breland & HARDY",74,34,3
96,Already Dead,Juice WRLD,,,
97,No Love,Summer Walker & SZA,-,83,1
98,23,Sam Hunt,,,
99,Family Ties,Baby Keem & Kendrick Lamar,81,81,4

In [84]:
# close the driver
driver.close()

## 7. Scrape the details of Data science recruiters from naukri.com.
#### Url = https://www.naukri.com/
#### You have to find the following details:
    A) Name
    B) Designation
    C) Company
    D) Skills they hire for
    E) Location
#### Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and click on search. All this should be done through code

In [2]:
# connect to webdriver
driver = webdriver.Chrome(r"C:/Users/DELL/Downloads/chromedriver_win32/chromedriver.exe")

# get webpage
driver.get("https://www.naukri.com/")
driver.maximize_window()

<ipython-input-2-c0ac0c8e40c3>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:/Users/DELL/Downloads/chromedriver_win32/chromedriver.exe")

In [3]:
#click on Browse All Recruiters
driver.get(driver.find_element_by_xpath("//a[@title='Search Recruiters']").get_attribute("href"))

#Search for Data Science Recruiters
driver.find_element_by_xpath("//input[@class='sugInp']").send_keys("Data Science")
driver.find_element_by_xpath("//button[@class='fl qsbSrch blueBtn']").click()

<ipython-input-3-7107d97c6e03>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.get(driver.find_element_by_xpath("//a[@title='Search Recruiters']").get_attribute("href"))
<ipython-input-3-7107d97c6e03>:5: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_xpath("//input[@class='sugInp']").send_keys("Data Science")
<ipython-input-3-7107d97c6e03>:6: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_xpath("//button[@class='fl qsbSrch blueBtn']").click()

In [6]:
#Scrap all tags

Name=[]
Designation=[]
Company=[]
Skills=[]
Location=[]
try:
    nameTag=driver.find_elements_by_xpath("//span[@class='fl ellipsis']")
    Name.extend([i.text for i in nameTag])
except:
    Name.append("-")
try:
    desTag=driver.find_elements_by_xpath("//span[@class='ellipsis clr']")
    Designation.extend([i.text for i in desTag])
except:
    Designation.append("-")

try:
    comTag=driver.find_elements_by_xpath("//a[@class='ellipsis']")[1::2]
    Company.extend([i.text for i in comTag])
except:
    Company.append("-")
    
try:
    skill=driver.find_elements_by_xpath("//div[@class='hireSec highlightable']")
    Skills.extend([i.text for i in skill])
except:
    Skills.append("-")

try:
    locTag=driver.find_elements_by_xpath("//small[@class='ellipsis']")
    try:
        Location.extend([i.text for i in locTag])
    except:
        Location.append("-")
except:
    Location.append("-")

<ipython-input-6-31452ecf4b18>:9: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  nameTag=driver.find_elements_by_xpath("//span[@class='fl ellipsis']")
<ipython-input-6-31452ecf4b18>:14: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  desTag=driver.find_elements_by_xpath("//span[@class='ellipsis clr']")
<ipython-input-6-31452ecf4b18>:20: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  comTag=driver.find_elements_by_xpath("//a[@class='ellipsis']")[1::2]
<ipython-input-6-31452ecf4b18>:26: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  skill=driver.find_elements_by_xpath("//div[@class='hireSec highlightable']")
<ipython-input-6-31452ecf4b18>:32: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  locTag=driver.find_elements_by_xpath("//small[@class='ellipsis']")

In [9]:
#Create Dataframe

df=pd.DataFrame()
df["name"]=Name
df['Designation']=Designation
df['Company']=Company
df['Skills_hireFor']=Skills
df['Location']=Location
df

,name,Designation,Company,Skills_hireFor,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Chennai
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
8,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Indore
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Bengaluru / Bangalore
10,Priyanka Akiri,HR Manager,Infinitive Software Solutions,"Oracle Dba, Data Science, Data Warehousing, ET...",Hyderabad
11,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Hyderabad / Secunderabad
12,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
13,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Mumbai
14,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Hyderabad / Secunderabad
15,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,"React.js, Data Science, Java, Front End, Busin...",Chandigarh
16,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
17,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Pune
18,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Pune
19,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Navi Mumbai
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Cochin
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Delhi
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
23,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Pune
24,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
25,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Pune
26,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Bengaluru / Bangalore
27,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Bengaluru / Bangalore
28,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",Delhi
29,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Hyderabad / Secunderabad
30,Avodha,Business Development Associate,Nikitha Palaparthi,"Ethical Hacking, Security Operations Center, S...",Mysoru / Mysore
31,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Bengaluru / Bangalore
32,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",Bengaluru / Bangalore
33,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",New Delhi
34,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",Chennai
35,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Aligarh
36,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Salt Lake City
37,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Pune
38,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Bengaluru / Bangalore
39,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Mumbai
40,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Indore
41,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Bengaluru / Bangalore
42,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",MYSORE
43,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",Hyderabad / Secunderabad
44,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Bengaluru / Bangalore
45,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Mumbai
46,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",Hyderabad / Secunderabad
47,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Manage...",Bengaluru / Bangalore

In [10]:
#close the driver
driver.close()

## 8. Scrape the details of Highest selling novels.
#### Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/
#### You have to find the following details:
    A) Book name
    B) Author name
    C) Volumes sold
    D) Publisher
    E) Genre

In [27]:
# connect to webdriver
driver = webdriver.Chrome(r"C:/Users/DELL/Downloads/chromedriver_win32/chromedriver.exe")

# get webpage
driver.get("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare")
driver.maximize_window()

<ipython-input-27-c3648b123eb0>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:/Users/DELL/Downloads/chromedriver_win32/chromedriver.exe")

In [28]:


books=[]
genre=[]
try:
    bokks=driver.find_elements_by_xpath("//td[@class='left']")
    books.extend([i.text for i in bokks])
except:
    books.append("-")
    
try:
    genreTag=driver.find_elements_by_xpath("//td[@class='last left']")
    genre.extend([i.text for i in genreTag])
except:
    genre.append("-")

<ipython-input-28-cb4e6c0b3e6a>:4: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  bokks=driver.find_elements_by_xpath("//td[@class='left']")
<ipython-input-28-cb4e6c0b3e6a>:10: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  genreTag=driver.find_elements_by_xpath("//td[@class='last left']")

In [29]:
title=books[1::5]
author=books[2::5]
volSold=books[3::5]
publisher=books[4::5]

In [30]:
df=pd.DataFrame()
df['BookName']=title
df['Author']=author
df['Volume_Sold']=volSold
df['Publisher']=publisher
df['genre']=genre
df

,BookName,Author,Volume_Sold,Publisher,genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [ ]:
#Close the driver
driver.close()

## 9. Scrape the details most watched tv series of all time from imdb.com.
#### Url = https://www.imdb.com/list/ls095964455/
#### You have to find the following details:
    A) Name
    B) Year span
    C) Genre
    D) Run time
    E) Ratings
    F) Votes

In [9]:
# connect to webdriver
driver = webdriver.Chrome(r"C:/Users/DELL/Downloads/chromedriver_win32/chromedriver.exe")

# get webpage
driver.get("https://www.imdb.com/list/ls095964455/")
driver.maximize_window()

<ipython-input-9-f66cd9aa95aa>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:/Users/DELL/Downloads/chromedriver_win32/chromedriver.exe")

In [10]:
#Scrape all tags

name=[]
yearSpan=[]
genre=[]
runTime=[]
ratings=[]
votes=[]
try:
    nameTag=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a")
    name.extend([i.text for i in nameTag])
except:
    name.append("-")

try:
    yearSpantag=driver.find_elements_by_xpath("//span[@class='lister-item-year text-muted unbold']")
    yearSpan.extend([i.text for i in yearSpantag])
except:
    yearSpan.append("-")
    

try:
    genreTag=driver.find_elements_by_xpath("//span[@class='genre']")
    genre.extend([i.text for i in genreTag])
except:
    genre.append("-")
    
try:
    runTimeTag=driver.find_elements_by_xpath("//span[@class='runtime']")
    runTime.extend([i.text for i in runTimeTag])
except:
    runTime.append("-")
    
try:
    ratingsTag=driver.find_elements_by_xpath("//span[@class='ipl-rating-star__rating']")
    ratings.extend([i.text for i in ratingsTag[::23]])
except:
    ratings.append("-")
    
try:
    votesTag=driver.find_elements_by_xpath("//span[@name='nv']")
    votes.extend([i.text for i in votesTag])
except:
    votes.append("-")

<ipython-input-10-b2015785bef7>:10: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  nameTag=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a")
<ipython-input-10-b2015785bef7>:16: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  yearSpantag=driver.find_elements_by_xpath("//span[@class='lister-item-year text-muted unbold']")
<ipython-input-10-b2015785bef7>:23: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  genreTag=driver.find_elements_by_xpath("//span[@class='genre']")
<ipython-input-10-b2015785bef7>:29: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  runTimeTag=driver.find_elements_by_xpath("//span[@class='runtime']")
<ipython-input-10-b2015785bef7>:35: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  ratingsTag=driver.find_elements_by_xpath("//span[@class='ipl-rating-star__rating']")
<ipython-input-10-b2015785bef7>:41: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  votesTag=driver.find_elements_by_xpath("//span[@name='nv']")

In [11]:
#CREATE DATAFRAME

df=pd.DataFrame()
df['Name']=name
df['YearSpan']=yearSpan
df['Ratings']=ratings
df['RunTime']=runTime
df['Genre']=genre
df['Votes']=votes
df

,Name,YearSpan,Ratings,RunTime,Genre,Votes
0,Game of Thrones,(2011–2019),9.2,57 min,"Action, Adventure, Drama","1,928,166"
1,Stranger Things,(2016– ),8.7,51 min,"Drama, Fantasy, Horror","950,289"
2,The Walking Dead,(2010–2022),8.2,44 min,"Drama, Horror, Thriller","921,399"
3,13 Reasons Why,(2017–2020),7.5,60 min,"Drama, Mystery, Thriller","276,067"
4,The 100,(2014–2020),7.6,43 min,"Drama, Mystery, Sci-Fi","236,334"
...,...,...,...,...,...,...
95,Reign,(2013–2017),7.5,42 min,"Drama, Fantasy","47,126"
96,A Series of Unfortunate Events,(2017–2019),7.8,50 min,"Adventure, Comedy, Drama","57,922"
97,Criminal Minds,(2005–2020),8.1,42 min,"Crime, Drama, Mystery","182,824"
98,Scream: The TV Series,(2015–2019),7.1,45 min,"Comedy, Crime, Drama","38,225"
99,The Haunting of Hill House,(2018),8.6,572 min,"Drama, Horror, Mystery","217,651"

In [12]:
#close the driver
driver.close()

## 10. Details of Datasets from UCI machine learning repositories.
#### Url = https://archive.ics.uci.edu/
#### You have to find the following details:
    A) Dataset name
    B) Data type
    C) Task
    D) Attribute type
    E) No of instances
    F) No of attribute
    G) Year
#### Note: - from the home page you have to go to the ShowAllDataset page through code.

In [13]:
# connect to webdriver
driver = webdriver.Chrome(r"C:/Users/DELL/Downloads/chromedriver_win32/chromedriver.exe")

# get webpage
driver.get(" https://archive.ics.uci.edu/")
driver.maximize_window()

<ipython-input-13-f8cd5960c617>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:/Users/DELL/Downloads/chromedriver_win32/chromedriver.exe")

In [14]:
# CLICK ON VIEW ALL DATASET
driver.get(driver.find_elements_by_xpath("//span[@class='normal']/b/a")[0].get_attribute('href'))

<ipython-input-14-19293f43605b>:2: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  driver.get(driver.find_elements_by_xpath("//span[@class='normal']/b/a")[0].get_attribute('href'))

In [15]:
# Scrape all tag

data=[]
try:
    tag=driver.find_elements_by_xpath("//td//p[@class='normal']")
    data.extend([i.text for i in tag[8:4362]])
except:
    data.append('-')

<ipython-input-15-4e0b4f401dba>:5: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  tag=driver.find_elements_by_xpath("//td//p[@class='normal']")

In [16]:
#slicing dataset

dtset=data[::7]
dtype=data[1::7]
task=data[2::7]
attTypeType=data[3::7]
no_instances=data[4::7]
no_att=data[5::7]
year=data[6::7]

In [17]:
# create dataframe
df=pd.DataFrame()
df['datasetName']=data[::7]
df['dataTypes']=data[1::7]
df['task']=data[2::7]
df['AttributrType']=data[3::7]
df['noOfInstances']=data[4::7]
df['noOFAttribute']=data[5::7]
df['year']=data[6::7]
df

,datasetName,dataTypes,task,AttributrType,noOfInstances,noOFAttribute,year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021

In [18]:
#close the driver
driver.close()

![thankyou](https://i.pinimg.com/originals/ca/38/3c/ca383c3d1c3ac6809a86c759b576e6f3.gif)